#!/usr/bin/env bash
# Installs web server - Nginx

sudo apt-get update -y

# Install Nginx
sudo apt install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Start nginx service
sudo service nginx start
