#!/usr/bin/env bash
# Configures web server - Nginx - to redirect

sudo apt-get update -y

# Install Nginx
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
# Start nginx service
sudo service nginx restart
