#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data based on 102-lets_parse_apache_logs
awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
