#!/usr/bin/env bash
#This script is displaying "Best School" 10 times, but adds "Hi" at the 9th iteration
count=1

while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
		echo "Best School"
	fi
	((count++))
done
