#!/usr/bin/env bash
#This script is displaying "bad luck" and "good luck" for 4th and 8th loop respectively and displays Best School for the other iterations
count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	count=$((count+1))
done
