#!/usr/bin/env bash
# This script installs the ufw firewall and setup a few rules on web-01
# Configure ufw so that it blocks all incoming traffic,
# except the following TCP ports: 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

apt-get update
apt-get install ufw -y
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw --force disable
ufw --force enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
